# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = "0.1.dev4+g7cb2a75.d20220914"
__version_tuple__ = version_tuple = (0, 1, "dev4", "g7cb2a75.d20220914")
